<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RunAOTCompilation>true</RunAOTCompilation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmBitcodeCompileOptimizationFlag>-O1</WasmBitcodeCompileOptimizationFlag>
    <EmccCompileOptimizationFlag>-O1</EmccCompileOptimizationFlag>
  </PropertyGroup>


  <ItemGroup>

    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.118.0-nightly.27" />


    <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="8.3.1-preview.1.2" />
    <NativeFileReference Include="$(HarfBuzzSharpStaticLibraryPath)\3.1.56\st\*.a" />

    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="3.118.0-nightly.27" />
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.56\st\*.a" />
  </ItemGroup>


</Project>
